### ISSUE TITLE
Bug when toggling create/select sandbox

### ISSUE THREAD

**Issue by sigdestad** [enonic/cli-enonic#114]
As can be seen from the screenshot below, moving cursor up and down is buggy.

Bug exists in the 1.0.0 release.

<img width="577" alt="Screenshot 2019-03-14 at 21 32 46" src="https://user-images.githubusercontent.com/482228/54389987-abf2b600-46a1-11e9-9e3f-1339f5aa0768.png">

**Comment by pmi** [comment]
Hm, I can not  reproduce it on windows pc.
But either way, it's the prompt library issue and I updated it to the latest version 1.8.2.
See if this is fixed now.

**Comment by alansemenov** [comment]
@sigdestad are you still getting this on the last version of CLI?

**Comment by sigdestad** [comment]
Yes, I am still getting it.
Reproducing consistently when choosing XP distro within "project create". Selector works perfectly everywhere else. Must be possible to fix!

**Comment by sigdestad** [comment]
Also same bug is in 1.0.4-next that Pavel sent us.
