### ISSUE TITLE
CLI does not support paths with space

### ISSUE THREAD

**Issue by sigdestad** [enonic/cli-enonic#117]
Given the following home directory: c:/users/sandra moen/ cli will fail.

We need to handle space in any path used by the CLI.
This is a critical error, and must be fixed ASAP.

Test carefully, and release a 1.0.2.

**Comment by pmi** [comment]
There is a known issue in golang https://github.com/golang/go/issues/17149
Trying to workaround it

**Comment by pmi** [comment]
Short description: windows' cmd.exe was incorrectly parsing arguments by stripping outer quotes completely screwing it in case of more than 1 argument
Full desc here: https://github.com/Microsoft/WSL/issues/2835#issuecomment-364475668

**Comment by sigdestad** [comment]
Solved it then?

**Comment by sigdestad** [comment]
The Windows problem seems to be fixed. We have not yet been able to test the same behaviour on linux/mac. But will do this later.
