### ISSUE TITLE
CRITIAL: Problems upgrading enonic cli with brew..

### ISSUE THREAD

**Issue by sigdestad** [enonic/cli-enonic#118]
Just tried upgrading to latest release 1.0.2, and got this error:

`~/doc-xp$ brew upgrade enonic
==> Upgrading 1 outdated package:
enonic/cli/enonic 1.0.0 -> 1.0.2
==> Upgrading enonic/cli/enonic 
Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences.

==> Installing dependencies for enonic/cli/enonic: go
==> Installing enonic/cli/enonic dependency: go
==> Downloading https://homebrew.bintray.com/bottles/go-1.12.1.mojave.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/6a/6a8b39eb96935992a90c8da4bcd26f9865875342c2894108f8a22f8af4a9a507?__gda__=exp=1554457615~h
######################################################################## 100.0%
==> Pouring go-1.12.1.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/go/1.12.1: 9,794 files, 452.6MB
==> Installing enonic/cli/enonic
==> Cloning https://github.com/enonic/cli-enonic.git
Updating /Users/tsi/Library/Caches/Homebrew/enonic--git
From https://github.com/enonic/cli-enonic
 * [new tag]         1.0.2      -> 1.0.2
==> Checking out tag 1.0.2
Previous HEAD position was 4d54912 Released version 1.0.0
HEAD is now at c6798f1 CLI does not support paths with space #117
HEAD is now at c6798f1 CLI does not support paths with space #117
==> go build -ldflags -X main.version=1.0.2 -X main.commit=c6798f1786f05aee9fdd3f2bf7e220eba242d24d -X main.date=2019-04-05 -o /usr/local/Ce
Last 15 lines from /Users/tsi/Library/Logs/Homebrew/enonic/01.go:
go: finding github.com/BurntSushi/toml v0.3.1
go: finding github.com/pelletier/go-buffruneio v0.2.0
go: finding github.com/kevinburke/ssh_config v0.0.0-20180830205328-81db2a75821e
go: finding github.com/kballard/go-shellquote v0.0.0-20180428030007-95032a82bc51
go: finding github.com/pkg/errors v0.8.1
go: finding github.com/Masterminds/semver v1.4.2
go: finding gopkg.in/warnings.v0 v0.1.2
go: finding gopkg.in/src-d/go-billy.v4 v4.3.0
go: finding gopkg.in/src-d/go-git.v4 v4.8.0
go: finding golang.org/x/net v0.0.0-20181114220301-adae6a3d119a
go: finding golang.org/x/crypto v0.0.0-20181126093934-9eb0be3963ea
go: finding github.com/mitchellh/go-homedir v1.0.0
go: finding github.com/mattn/go-colorable v0.0.9
go: finding gopkg.in/cheggaaa/pb.v1 v1.0.27
go: error loading module requirements

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/enonic/homebrew-cli/issues

Error: Validation Failed: [{"message"=>"The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.", "resource"=>"Search", "field"=>"q", "code"=>"invalid"}]`

**Comment by jsi** [comment]
Where is 1.0.2?  -  Trying to upgrade, I only get this:

**Comment by sigdestad** [comment]
Maybe need to do tap first?

**Comment by jsi** [comment]
I did that, thinking it was madatory:

**Comment by alansemenov** [comment]
This is no longer relevant I guess
