### ISSUE TITLE
Sandbox delete: add -y flag to to be able to delete silently

### ISSUE THREAD

**Issue by pmi** [enonic/cli-enonic#119]
Most CLI commands support scripting by operating non-interactively as long as all necessary params are provided, but this is not the case with this one.

**Comment by sigdestad** [comment]
Hmm.. Thinking about this. Isn't it more normal to use -f (force) in such cases?

**Comment by pmi** [comment]
I like "f" more than "y", but we have "y" in dump load already so will need to change it there as well to be  consistent

**Comment by sigdestad** [comment]
Lets make it consistent thenn :-)
