### ISSUE TITLE
CLI adjustments based on usage

### ISSUE THREAD

**Issue by pmi** [enonic/cli-enonic#122]
1. Sort the list of starters by name. Not sure what the order is now but it keeps changing. Also, if “Custom repo” is the first choice in the list then it should be the one selected by default, but I believe that it’s not the most popular choice so maybe it should be in the bottom of the list. I also suggest distinguishing it somehow from the starters since it’s a totally different thing/wizard. Maybe something like

Starter 1
Starter 2
—————
Custom repo

2. After selecting a starter, CLI asks for the “Project name” (com.enonic.app.mytest). This is a bit confusing since it’s not a project name, it’s an application name (two steps later we ask for “Application version”).

3. When the project is created, we give a message “Project created in ‘path’” and then after linking project to the sandbox we show “Project linked to “Sandbox1” (without ever mentioning the project name and not 100% correct english in both messages). Would be nice with one message in the very end saying “Project “mytest” is successfully created in ‘path’ and linked to “Sandbox1””.

4. Can we go directly to the project folder after the project is created? That’s what 99% users will do anyway. It would be great to run “enonic project deploy” right away, without having to remember folder name to use in “cd …”.

5. When running “enonic sandbox delete” I get an option to create a new sandbox - looks a bit weird.

**Comment by sigdestad** [comment]
Pavel, I'm closing this task and creating one task per thing we want to fix, ok?

**Comment by pmi** [comment]
Sure
