### ISSUE TITLE
Improved listing of starters

### ISSUE THREAD

**Issue by sigdestad** [enonic/cli-enonic#123]
* Sort the list of starters by name.
* Add separator between custom repo and the rest, and place it last in the list
* Include a short description of the starters (use descriptions from API)

Starter 1 (Use this to win the war)
Starter 2 (Build your own barn)
—————
Custom repo

**Comment by pmi** [comment]
As far as I can see list separators are not supported by the lib we use https://github.com/AlecAivazis/survey#customizing-output

The rest is done.

**Comment by sigdestad** [comment]
Hi, I am reopening this one to make a small adjustment.
Can we get the description in normal font, and only keep the name of the starter in bold. like this:

*My cool starter* (Used to kick off cool projects)
*Vanilla starter* (what is this stuff?)

**Comment by pmi** [comment]
Spent whole day yesterday to make this work, but all in vain. This is not documented in the lib we use for selects, so I dove deep in the lib sources and tried to tap into the template engine they use, just to find out  that options are escaped and passed as plain strings.
So this doesn't look possible without modifying the lib :(

**Comment by sigdestad** [comment]
I see, what if we had an option that was simply called "---" and handle when people select this by showing the prompt once more? I guess almost noone will actually select it?

**Comment by sigdestad** [comment]
I guess this might be implemented with a different library, but here they use a separator (and it is not selectable - which is probably a bad idea anyway)

<img width="614" alt="Screenshot 2019-05-06 at 20 24 47" src="https://user-images.githubusercontent.com/482228/57246257-1b9b7680-703d-11e9-8f1c-174c261c6f0a.png">

**Comment by sigdestad** [comment]
Moving cursor up an down just skips the line smoothly.

**Comment by sigdestad** [comment]
Visually, this is at least very close to our stuff..

**Comment by sigdestad** [comment]
We'll place this task in the backlog for a while.

**Comment by sigdestad** [comment]
Hmm.. I just realized this task contains two things (the separator line, and the description).
Let's forget the separator line and just complete the description.

So, only thing remaining is to remove "bold" from the description
