### ISSUE TITLE
Enonic sandbox delete fails

### ISSUE THREAD

**Issue by sigdestad** [enonic/cli-enonic#125]
When running sandbox delete, CLI asks if you want to create a new project?

**Comment by pmi** [comment]
Nope, it doesn't :)

**Comment by alansemenov** [comment]
Not a project but a sandbox

![image](https://user-images.githubusercontent.com/11612490/56039031-a4bbd800-5d33-11e9-894d-ca43f917f14b.png)

**Comment by pmi** [comment]
Ah, ok
