### ISSUE TITLE
Publish Enonic CLI in Linux/Ubuntu repository

### ISSUE THREAD

**Issue by alansemenov** [enonic/cli-enonic#128]
Uploading it to Launchpad seems to be enough for apt-get to be able to retrieve it.

http://packaging.ubuntu.com/html/packaging-new-software.html
https://launchpad.net/+tour/ppa
https://help.launchpad.net/Packaging/PPA/Uploading

**Comment by sigdestad** [comment]
Any news on this Pavel?

**Comment by pmi** [comment]
Published to snapcraft, can be seen at https://snapcraft.io/enonic
To install in linux run `sudo snap install enonic`

Launchpad publishing turned out to be a real PITA.
