### ISSUE TITLE
enonic project wrapper

### ISSUE THREAD

**Issue by ComLock** [enonic/cli-enonic#131]
After setting gradleVersion = 5.0

I run ```./gradlew wrapper``` in order to upgrade gradle.

However since the environment is wrong I get:
```java.lang.UnsupportedClassVersionError: com/enonic/gradle/xp/BasePlugin```

Also see #130

**Comment by alansemenov** [comment]
This is not a problem of CLI. You should use correct version of the gradle plugins that are compatible with version of Java from $JAVA_HOME.

**Comment by ComLock** [comment]
If Enonic XP ships with a bundled Java. It would be nice to export that Java to the environment somehow.
