### ISSUE TITLE
pass on arguments to gradle

### ISSUE THREAD

**Issue by ComLock** [enonic/cli-enonic#132]
In order to be certain a build is perfect I've become used to running
```./gradlew clean build deploy```

It's not possible to run
```enonic project clean build deploy```

You have to do
```enonic project clean && enonic project build && enonic project deploy```

Which is not such a nice command.

**Comment by alansemenov** [comment]
Yes, totally agree with this one. @pmi can we (with whatever 3rd party lib we are now using to parse CLI commands) combine several supported commands in one line and execute them in specified order?

**Comment by pmi** [comment]
Introduced `enonic project gradle` command that passes all arguments to gradle, excluding flags (args prefixed with -/--). [Docs here](https://github.com/enonic/cli-enonic/blob/master/docs/index.adoc#gradle)

**Comment by sigdestad** [comment]
I assume it is using gradlew, since we cannot know if people actually have installed Gradle + the fact that gradlew will match the starter ofcourse :-)

**Comment by pmi** [comment]
@sigdestad, yes it uses gradlew!
