### ISSUE TITLE
enonic sandbox start in a project folder where sandbox is selected still prompts for select which sandbox

### ISSUE THREAD

**Issue by ComLock** [enonic/cli-enonic#136]
bug or feature?

**Comment by alansemenov** [comment]
@ComLock Neither. The initial design of "sandbox start" command assumed that user always selects which sandbox to start. But I agree that in the case when you start it from the project folder **which already has .enonic file** that specifies which sandbox to use, we should just start this sandbox without asking.

**Comment by alansemenov** [comment]
I also think that when there's just one sandbox in the system (which will be 99% of cases) CLI shouldn't ask either, but let's leave this out of this task.

**Comment by sigdestad** [comment]
Ahem, this is actuslly intentional behaviour... Lets discuss before we change it

**Comment by alansemenov** [comment]
How is asking for sandbox when starting it **from inside the project already linked** to a sandbox intended behaviour?.. Especially when there's just one sandbox at all.

**Comment by pmi** [comment]
Agree with @ase that it's a clever thing to start sandbox that is configured for project if you're inside that  project folder ! I made the changes for you to test, but we can revert them if not needed.

**Comment by pmi** [comment]
Made sure you can override default sandbox by running `enonic project sandbox WhateverBox` from project folder if you so desire.
