### ISSUE TITLE
enonic dump load -> 0.00% 403 HTTP 403 Forbidden

### ISSUE THREAD

**Issue by ComLock** [enonic/cli-enonic#137]
During the loading of the dump the password for the su user is overwritten.
At this point the progress connection fails.
And you end up with 0.00% and 403 HTTP 403 Forbidden.

The dump is loaded fine though.

@GlennRicaud says we should use the session for getting progress rather than using the username and password.

The documentation should perhaps also be updated.
https://developer.enonic.com/docs/xp/stable/release/upgrade#3_upgrade_and_load

**Comment by alansemenov** [comment]
@pmi this is quite critical. we need to change the progress update to not use credentials, as [described by Glenn here](https://github.com/enonic/cli-enonic/issues/62)

**Comment by GlennRicaud** [comment]
Okay without implementing everything I mentionned in the issue.
The idea is to at least reuse the session ID for the progress requests

**Comment by pmi** [comment]
@ComLock @ase @gri There is a [--new-auth flag](https://github.com/enonic/cli-enonic/blob/master/docs/index.adoc#load) for that currently, you know that right ? ;)

**Comment by pmi** [comment]
Although it's not as natural to use as session ID of course

**Comment by ComLock** [comment]
@pmi I do not know. Also it's the 200+ developers out there that should not have to know everything, but be able to follow an upgrade documentation...

**Comment by sigdestad** [comment]
So, what we _SHOULD_ do in this case is to disassociate the websocket from the user session i.e. making the websocket that feeds the progress available for anyone to listen to.

So, my point is that we do not need to limit progress info to the su user (which is deleted during the load anyway).

Sessions do not solve this in any way, you only need a stable websocket handle...
