### ISSUE TITLE
look up existing docs url when creating new project with custom repo flag

### ISSUE THREAD

**Issue by pmi** [enonic/cli-enonic#139]

**Comment by sigdestad** [comment]
Hi Pavel, what does this task do?

**Comment by pmi** [comment]
Hi Thomas, 
It is something Alan found when testing CLI.
Doing `enonic project create -r starter-vanilla` is essentially the same as doing `enonic project create` and selecting starter-vanilla from the list. But the difference is starter list also has the docs url info, while -r flag does not load starters and therefore docs url to suggest after project is created.
