### ISSUE TITLE
Output of some cli commands sent to stderr

### ISSUE THREAD

**Issue by gbbirkisson** [enonic/cli-enonic#144]
The output of `enonic sandbox ls` is sent to STDERR. You can verify by running `enonic sandbox ls 2> /dev/null`. That provides no output. This makes it a hassle to pipe the output to other commands. To pipe the output to cat currently you have to do:
```
enonic sandbox ls 2>&1 >/dev/null | cat
```
Usually it should only be:
```
enonic sandbox ls | cat
```
I haven't checked other commands but in general most standard output should go STDOUT.

**Comment by pmi** [comment]
Good point !
Actually I think cli sends everything to stderr, so will go through every command to redirect usefull info to stdout.
