### ISSUE TITLE
CLI does not exit on SIGINT (Crtl + C) when creating new projects

### ISSUE THREAD

**Issue by gbbirkisson** [enonic/cli-enonic#150]
This problem was observed on Arch Linux. 

Steps to reproduce:
* Run `enonic project create`
* Select starter in menu.
* When promoted for project name try to end the program: `CTRL + C`

Program should quit but instead it continues setting up the project.

**Comment by alansemenov** [comment]
Experienced the same as well. Same problem with other wizards, like `sandbox create`
