### ISSUE TITLE
latest, stable and unstable?

### ISSUE THREAD

**Issue by ComLock** [enonic/cli-enonic#153]
Came across a guy that was unsure wether 7.0.2 was a stable version of Enonic.

So I think we should do something like this:

```
? Enonic XP distribution:  [Use arrows to move, type to filter]
  mac-sdk-7.0.3-RC1 (unstable)
> mac-sdk-7.0.2 (latest, stable)
  mac-sdk-7.0.1 (stable)
  mac-sdk-7.0.0 (stable)
```

Perhaps with some nice colors on the parantheses, red for unstable, green for stable?

**Comment by sigdestad** [comment]
Excellent idea!

**Comment by ComLock** [comment]
Perhaps also a flag for showing unstable versions.

**Comment by jsi** [comment]
I think the default should be to show only stable releases.  -  But it is a good idea to have a config setting that can override this to also show RCs, Betas and even Snapshots for techies that might want to see such releases.

**Comment by sigdestad** [comment]
Yes, we should only show (latest) and have a flag -a or similar to show all releases...

**Comment by sigdestad** [comment]
Items in list should by defsult be considered stable
