### ISSUE TITLE
Two click upgrade on enonic sandbox start?

### ISSUE THREAD

**Issue by ComLock** [enonic/cli-enonic#154]
Check for new version of XP and some point in time, store that somewhere.
On enonic sandbox start, check locally whether new stable version available.

Upgrade to 7.0.3 (y/N) ? (Will continue automatically with 7.0.2 in 3)
Upgrade to 7.0.3 (y/N) ? (Will continue automatically with 7.0.2 in 2)
Upgrade to 7.0.3 (y/N) ? (Will continue automatically with 7.0.2 in 1)
Starting 7.0.2

--
Upgrade to 7.0.3 (y/N) ? y
Downloading, Installing, Starting 7.0.3

**Comment by alansemenov** [comment]
We give a message now if the last version check was more than 30 days ago.
