### ISSUE TITLE
enonic project test

### ISSUE THREAD

**Issue by ComLock** [enonic/cli-enonic#157]
To run tests.

Workaround:

```sh
enonic project gradle clean build test
```

**Comment by alansemenov** [comment]
Not sure about this one. We don't know if the project has tests or not. It's like implementing `enonic project publish` not knowing if publishing is supported in the build. I suggest we keep basic build commands (`clean`, `build`, `deploy`) and leave the rest to `project gradle...`

**Comment by ComLock** [comment]
First a lesson: One has to run build or the tests beeing run are from the previous compile.

Perhaps gradle test should depend on build.

**Comment by ComLock** [comment]
Node developers are used to ```npm test``` which is the same as ```npm run test``` and will throw Error: no test specified if there is no test script defined in package.json.
