### ISSUE TITLE
Show progress while deleting a sandbox

### ISSUE THREAD

**Issue by ComLock** [enonic/cli-enonic#158]
This never finish, even though the distro folder is gone from ~/.enonic/distributions

```sh
$ enonic sandbox del
? Select sandbox to delete: name ( mac-sdk-7.0.0 )
? WARNING: This can not be undone ! Do you still want to delete sandbox 'name' ? Yes
? Distro 'mac-sdk-7.0.0' is not used any more. Do you want to delete it ? Yes
```

**Comment by ComLock** [comment]
Hmm it just took a very long time.

```sh
Sandbox 'name' deleted.
```

Perhaps it's possible to make some kinda progress bar?

**Comment by alansemenov** [comment]
I don't think it's possible to retrieve progress for deletion but we could show some kind of animation, like _Sandbox "My sandbox" is being deleted..._ with animating dots.
