### ISSUE TITLE
FR: Hide password when dump upgrading

### ISSUE THREAD

**Issue by Slideshow776** [enonic/cli-enonic#167]
Requesting feature to hide password when dum upgrading.
![image](https://user-images.githubusercontent.com/4059636/63684628-a75c2d00-c7fd-11e9-9f2a-95a0e39af013.png)

**Comment by alansemenov** [comment]
Replace it with "*" maybe?

**Comment by Slideshow776** [comment]
> Replace it with "*" maybe?

Possibly, or just do it the Linux way by not showing anything?

**Comment by sigdestad** [comment]
One * per character could be nice
