### ISSUE TITLE
Flag to list B- and RC- versions of the distro on "create sandbox"

### ISSUE THREAD

**Issue by jsi** [enonic/cli-enonic#168]
When creating a sandbox, the selection of versions should only include releases.  All RCs, Betas and Alphas should be hidden.  This should be the same, both with `create sandbox` and when creating a sandbox as part of creating a project.

But, we do need the possibility to create sandboxes with all versions, so `create sandbox`, should take a flag `-allVersions` / `-av` that brings up RCs, Bs and As among the possible sources for a new sandbox.  This is needed for testing purposes by Enonic employees and possibly some early adopting customers.  It does not need to be applied to creating a sandbox from the create project command.

**Comment by jsi** [comment]
It should be discussed if -av should include snapshots.  My personal opinion is that there may be a few situations where that would be nice, but it could also easily become too many choices and a lot of noise, so I am not really sure about what to recommend on this.

**Comment by alansemenov** [comment]
I don't think we should include snapshots. We could have some hidden flag for ourselves to be able to select a snapshot, but for the externals it should not be available

**Comment by sigdestad** [comment]
Could we call the option -a instead?
Agree with Alan that snapshots should not be listed. We could add a -d or -v option to specify exact version to download?

**Comment by alansemenov** [comment]
See also https://github.com/enonic/cli-enonic/issues/153

**Comment by pmi** [comment]
Added `--all` or `-a` flag to list all versions except snapshots.
@sigdestad There is a `-v` flag to use specific version already, but I made changes to look for non-stable versions as well, if `-v` param contains signs of a prerelease.
