### ISSUE TITLE
Start distro with a symlink when used through snapcraft

### ISSUE THREAD

**Issue by pmi** [enonic/cli-enonic#173]
Snapcraft permissions are not supposed to grant execute rights to `.enonic` folder (although it works on some distros), so in order to be able to start distro on all linux distros we need to create a symlink to it as described here:

https://forum.snapcraft.io/t/request-for-auto-connection-for-enonic/11733/30

**Comment by alansemenov** [comment]
Will be done in https://github.com/enonic/cli-enonic/issues/193
