### ISSUE TITLE
Add support for proxy

### ISSUE THREAD

**Issue by RF0** [enonic/cli-enonic#175]
At [customer-name] there is challenges using the enonic-cli in build-scripts on servers because all external http(s) requests has to go through a proxy. All requests in enonic-cli should respect proxy settings or include parameter for sending in which proxy to use.

**Comment by realmunk** [comment]
👍

**Comment by sigdestad** [comment]
We will add support for environment variable ala this
ENONIC_CLI_HTTP_PROXY=<http://somewhere:port>

It will work similar to the existing environment variables. https://developer.enonic.com/docs/enonic-cli/master#configuration

**Comment by pmi** [comment]
Done, updated docs https://developer.enonic.com/docs/enonic-cli/master#configuration

Shared it with Trond Erling Hundal to test, and it worked for him. 
But both of us are at homes so we could not test it in a real life environment.

**Comment by sigdestad** [comment]
Great, lets release it (new feature version) and fix if anyone reports bugs?

Have you tested that everything works fine without proxying as well? So we don't get any regressions?

**Comment by pmi** [comment]
Yep, confirm that it works both with and without proxy !
