### ISSUE TITLE
Add global flag to suppress user input prompts

### ISSUE THREAD

**Issue by gbbirkisson** [enonic/cli-enonic#176]
I have been working on using the CLI in a CircleCI and Github Actions pipelines. If the CLI promts the "user" for input the pipeline stalls. This renders some client actions unusable in pipelines. Please support disabling these prompts so we can use the CLI in pipelines.

This also adds the requirement that the values the CLI is asking for when prompting, should be passed in with some flags when needed in the pipeline.

**Comment by pmi** [comment]
@gbbirkisson Can you name the commands you had problems with ?
I had this scenario in mind when developed CLI and most of the commands should run non-interactively granted all required params are there.

**Comment by gbbirkisson** [comment]
I think it was when doing `enonic project install` but I tested it now and it to works. The documentation also state that it works. I must have made a mistake when I tested this earlier. Closing this issue. Sorry for the bother :)
