### ISSUE TITLE
keep-alive issue in enonic cms reprocess

### ISSUE THREAD

**Issue by alansemenov** [enonic/cli-enonic#179]
```
root@test:/var/enonic-xp/xxx/deploy# enonic cms reprocess
Enter target content path (<branch-name>:<content-path>): master:/
Reprocessing...Unable to connect to remote service: Post http://localhost:4848/content/reprocess: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

Tips from the customer:

> enonic-cli uses net/http synchronously and will time out after 1m on i.e. enonic cms reprocess.
> This is an obvious design issue, needs to either async/long-poll or tcp keepalive.
> For instance a cms reprocessing can easily take more than 1min:

**Comment by pmi** [comment]
CLI is able to make async task polling, but that requires server command to be an async task with progress reporting.

Currently following commands are tasks and polled by CLI:
- Exporting data, 
- Importing data,
- Loading dump,
- Creating dump,
- Upgrading dump, 
- Vacuuming _(not used)_

So the bottom line is, ContentResource.reprocess() needs to support polling first for the CLI to use it.

**Comment by alansemenov** [comment]
@GlennRicaud any objections against adding polling support to `reprocess`?

**Comment by GlennRicaud** [comment]
Sounds good.
But when doing these changes in the CLI, keep in mind that.
- CLI should work with 7.0, 7.1 XP distributions
- Old CLIs should work with >=7.2 distributions

**Comment by sigdestad** [comment]
We do not need old CLI to work with newer XP's.

**Comment by GlennRicaud** [comment]
I did not think it was an internal API. I have seen customers use this API with their own script. Breaking it is not advisable.

**Comment by pmi** [comment]
Created 2 PRs in cli-enonic as well as xp repos with new reprocess method instead of the old one. Let me know if we need a new reprocess method along with the old one to keep backwards compatibility.
https://github.com/enonic/cli-enonic/pull/180
https://github.com/enonic/xp/pull/7518

**Comment by alansemenov** [comment]
This one has to be updated as well, after updates to enonic/xp#7518

**Comment by pmi** [comment]
Updated PR
