### ISSUE TITLE
Enable global no-prompts flag

### ISSUE THREAD

**Issue by diegopasten** [enonic/cli-enonic#186]
Would be nice to turn off clever prompts from CLI, through an enviroment variable or similar.

For example when deleting last sandbox with a version of XP the user is needs to answer if they also want to delete the distro (since its unused). 

This creates problem for automation with bash/Jenkins. Jobs in Jenkins are marked as failed or stall forever as it doesn't know what to do when prompted.

**Comment by alansemenov** [comment]
We had [another request](https://github.com/enonic/cli-enonic/issues/176) for the same issue but it was dropped for some reason. We should be able to pass all prompted values via command-line parameters.
