### ISSUE TITLE
Show entire list of sandboxes in `sandbox start`

### ISSUE THREAD

**Issue by Slideshow776** [enonic/cli-enonic#190]
List of sandboxes is only 6 items long without scrolling. Even though it clearly says "use arrows to move" this may easily be missed and give a confusing or frustrating user experience.
This bug was created by wish of @alansemenov.

![image](https://user-images.githubusercontent.com/4059636/71579471-f8a66100-2afc-11ea-92ce-6f63a6cb9a50.png)

**Comment by alansemenov** [comment]
@pmi this seems to work correctly (the entire list of sandboxes is shown) when doing `sandbox list`

**Comment by pmi** [comment]
Sandbox list is not interactive and just prints everything out, while sandbox start uses select input, which can be configured to any reasonable amount, so I suggest just doubling it to say 12.

@alansemenov what do you think ?

**Comment by alansemenov** [comment]
@pmi can we fetch a list of sandboxes first, and then set the select input's maxlength to the length of this list? or does max length have to be hardcoded?

**Comment by pmi** [comment]
Yes, it has to be hardcoded, but we can set it to the length of the list as well. Is it what you desire ? :)

**Comment by alansemenov** [comment]
Ideally we should always show the full list since there's no visual indication that the list is scrollable.
