### ISSUE TITLE
CLI asks to start the sandbox that is already running

### ISSUE THREAD

**Issue by alansemenov** [enonic/cli-enonic#194]
1. Create and deploy a new project (`enonic project create` & `enonic project deploy`)
2. When deploying the project, CLI asks to select a sandbox to start. Select or set up one. Sandbox starts and project is deployed. Fine.
3. Now open another terminal tab and repeat the same steps - create and deploy another project
4. Select the same sandbox as for the first project. 

You will get a question about stopping the sandbox that is running to start it again (see screenshot below). This used to work perfectly fine before 1.1.0.

 
![image](https://user-images.githubusercontent.com/11612490/72261828-ec022c80-3615-11ea-8ce3-ff8fa45bf7fc.png)

**Comment by sigdestad** [comment]
This is urgent to fix.. 1.1.1 is needed
