### ISSUE TITLE
`latest` returns incorrect result when called the first time

### ISSUE THREAD

**Issue by alansemenov** [enonic/cli-enonic#197]
1. Make sure CLI is not installed
2. Install the latest version from **brew** or **scoop**
3. Execute `enonic latest`

Even though you're definitely on the latest version, you will get this:
```
Loading...
Local version: 1.1.1.
Latest available version is 1.1.1. Run 'brew upgrade enonic' to update CLI
```

4. Execute `enonic`
5. Now execute `enonic latest` again

This time version comparison is correct, but there's odd "_%_" in the end:

```
Loading...
You are using the latest version of Enonic CLI: 1.1.1%
```

**Comment by jsi** [comment]
You can even skip step 4.  Just executing `enonic latest` two times in a row will result in the two different messages.

But, the % at the end is actually just the prompt.  There is a missing lineshift at the end of the second message, after the verion number.  For med, I got: `...1.1.1sivesind>` :)
