### ISSUE TITLE
Enonic sandbox does not stop from detached mode

### ISSUE THREAD

**Issue by RagnarAlex** [enonic/cli-enonic#216]
Enonic sandbox does not stop from detached mode on CentOS7/macOS

[root@centos1 tmp]# enonic sandbox stop Sandbox1
No sandbox is currently running.
[root@centos1 tmp]#

[root@centos1 tmp]# ./enonic-changed sandbox start Sandbox1 -d
Extracted pid from file:  0
[root@centos1 tmp]# ps aux | grep enonicde.[root@centos1 tmp]#
root     14004 44.1  4.5 3197528 174924 pts/2  Sl   21:17   0:05 /root/.enonic/distributions/enonic-xp-linux-sdk-7.2.2/jdk/bin/java -XX:+CMSParallelRemarkEnabled -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=60 -XX:+ScavengeBeforeFullGC -XX:+CMSScavengeBeforeRemark -Dxp.install=/root/.enonic/distributions/enonic-xp-linux-sdk-7.2.2 -Dfile.encoding=UTF8 -Dnashorn.args=--no-deprecation-warning -Dmapper.allow_dots_in_name=true --add-opens java.base/java.net=ALL-UNNAMED --add-opens java.xml/com.sun.org.apache.xerces.internal.util=ALL-UNNAMED -classpath /root/.enonic/distributions/enonic-xp-linux-sdk-7.2.2/lib/* com.enonic.xp.launcher.LauncherMain -Dxp.home=/root/.enonic/sandboxes/Sandbox1/home
...

**Comment by gbbirkisson** [comment]
I still get: `No sandbox is currently running.`

Notice that the PIDs do not match, and when I try to stop the PID resets to 0.

```
$ ./test sandbox start test -d
Started sandbox 'test' in detached mode.

$ ps aux | grep enonic
gummi     542291  120  2.1 12175384 528272 pts/5 Sl   09:39   0:29 /home/gummi/.enonic/distributions/enonic-xp-linux-sdk-7.2.0/jdk/bin/java -XX:+CMSParallelRemarkEnabled -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=60 -XX:+ScavengeBeforeFullGC -XX:+CMSScavengeBeforeRemark -Dxp.install=/home/gummi/.enonic/distributions/enonic-xp-linux-sdk-7.2.0 -Dfile.encoding=UTF8 -Dnashorn.args=--no-deprecation-warning -Dmapper.allow_dots_in_name=true --add-opens java.base/java.net=ALL-UNNAMED --add-opens java.xml/com.sun.org.apache.xerces.internal.util=ALL-UNNAMED -classpath /home/gummi/.enonic/distributions/enonic-xp-linux-sdk-7.2.0/lib/* com.enonic.xp.launcher.LauncherMain -Dxp.home=/home/gummi/.enonic/sandboxes/test/home

$ cat ~/.enonic/.enonic
running = "test"
PID = 542286
SessionID = ""
LatestVersion = ""
LatestCheck = 0001-01-01T00:00:00Z

$ ./test sandbox stop test
No sandbox is currently running.

$ cat ~/.enonic/.enonic -p
running = ""
PID = 0
SessionID = ""
LatestVersion = ""
LatestCheck = 0001-01-01T00:00:00Z
```

**Comment by alansemenov** [comment]
@RuslanSey This was most likely fixed in https://github.com/enonic/cli-enonic/issues/220. To be tested after release of CLI 1.2.1

**Comment by alansemenov** [comment]
The fix didn't help so we still need to get this fixed

**Comment by alansemenov** [comment]
Fixed in https://github.com/enonic/cli-enonic/issues/465
