### ISSUE TITLE
enonic repo readonly command unnecessarily closes indices

### ISSUE THREAD

**Issue by rymsha** [enonic/cli-enonic#223]
`requireClosedIndex` is set to true which translates to closing index before change.

it tries to adjust `index.blocks.write`. It is a dynamic property and does not require index to be closed.

https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules.html

Change `requireClosedIndex` to `false` but verify if it still works.

**Comment by sigdestad** [comment]
Ah.. Sounds like a reasonably quick fix?

**Comment by rymsha** [comment]
Takes more time to test than to fix.

The best would to look through the code for similar commands. Maybe some of them also close indices unnecessarily
