### ISSUE TITLE
`enonic sandbox create --all` no longer shows snapshot distro versions

### ISSUE THREAD

**Issue by alansemenov** [enonic/cli-enonic#240]
Most likely after the latest separation of snapshots. We should find a way to retrieve snapshot versions from [here](https://repo.enonic.com/snapshot/com/enonic/xp/enonic-xp-mac-sdk/) and merge them with the main list.

7.5.0-SNAPSHOT, for example, should have been on this list:
![image](https://user-images.githubusercontent.com/11612490/91694567-0a00ab00-eb6d-11ea-8797-94318feb0081.png)

**Comment by sigdestad** [comment]
I disagree, snapshots should never be in this list, only ALPHA, BETA and RC's.
If you need a snapshot (which is generally not released), you should get it in some other way

**Comment by alansemenov** [comment]
True, `-all` is not for snapshots.
