### ISSUE TITLE
Just add client id and secret to source

### ISSUE THREAD

**Issue by gbbirkisson** [enonic/cli-enonic#245]

**Comment by rymsha** [comment]
https://www.oauth.com/oauth2-servers/client-registration/client-id-secret/

> If the developer is creating a “public” app (a mobile or single-page app), then you should not issue a client_secret to the app at all. This is the only way to ensure the developer won’t accidentally include it in their application. If it doesn’t exist, it can’t be leaked!

**Comment by sigdestad** [comment]
Can we talk to auth0 without such tokens?

**Comment by gbbirkisson** [comment]
As far as I can tell, we need the `client_secret` to refresh access tokens: https://auth0.com/docs/flows/call-your-api-using-the-device-authorization-flow

**Comment by rymsha** [comment]
The more I read the more I know.
CLI can also be considered a "device"
https://auth0.com/docs/flows/call-your-api-using-the-device-authorization-flow#sample-implementations

But there is no "secret" in sample only client_id
https://gist.github.com/panva/652c61e7d847e0ed99926c324fa91b36
