### ISSUE TITLE
Access denied to 'https://github.com/enonic/starter-myfirstwebapp.git'

### ISSUE THREAD

**Issue by thrdcircle** [enonic/cli-enonic#266]
```
PS C:\WINDOWS\system32> enonic project create -r starter-myfirstwebapp

? Project name com.example.myproject
? Destination folder myproject
? Project version 1.0.0-SNAPSHOT

Initializing project...
Could not connect to a remote repository 'https://github.com/enonic/starter-myfirstwebapp.git': mkdir myproject: Access is denied.
PS C:\WINDOWS\system32>
```

I'm following the instructions https://github.com/enonic/cli-enonic

I have XP CLI

Where do I place the github token? I'm not understanding the language "put it in ~/.config/goreleaser/github_token"
I don't see that path. Yes I have goreleaser and dep.

Thanks

**Comment by pmi** [comment]
@thrdcircle, The error you provided indicates that you do not have access rights to create _myproject_ folder inside `C:\WINDOWS\system32`.
To fix that try executing same command from `C:\Users\<username>` folder for instance.

Publishing is done by us for releasing new versions of enonic CLI to our scoop, brew and snapcraft repositories.
So you generally don't need that part, unless you want to set up your own repositories. In that case you will need to adjust `goreleaser.yml` file to your needs first.

**Comment by thrdcircle** [comment]
Thanks, that was my oversight.
