### ISSUE TITLE
The CLI doesn't handle symlinked distributions

### ISSUE THREAD

**Issue by thomasheartman** [enonic/cli-enonic#271]
I wanted to use the CLI with a distribution that's not located in the `~/.enonic/distributions` folder. To do that I attempted make the `enonic-xp-linux-7.6.1` directory into a symlink to the actual place on disk where the distribution was, but this didn't work. Instead, the CLI removed the symlink and started re-downloading the distribution.

I had expected the CLI to follow symlinks in the path.

I spoke to @gbi on the internal Slack and was told to report it as a bug.

## Issue

If you want to use a distribution stored outside of the regular `~/.enonic/distributions/` directory, using a directory symlink doesn't work.

## Expected behavior

The CLI should follow the symbolic link and use the distribution found after following the link.

## Actual behavior

The CLI removes the symlinked directory and installs the distribution.

## Workaround

This can be worked around by symlinking the children of the directory instead of the directory itself. @gbi suggested the following solution:

``` shell
ACTUAL_PATH=/path/to/my-distro
SYMLINK_PATH=~/.enonic/distributions/enonic-xp-linux-sdk-7.6.1

rm -r $SYMLINK_PATH
mkdir $SYMLINK_PATH

find $ACTUAL_PATH/ -maxdepth 1 \
    | grep -v '/$' \
    | xargs -L 1 basename \
    | xargs -I {} ln -s $ACTUAL_PATH/{} $SYMLINK_PATH/{}
```

Optionally, you can symlink every file and create a directory structure at point:

``` shell
ACTUAL_PATH=/path/to/my-distro
SYMLINK_PATH=~/.enonic/distributions/enonic-xp-linux-sdk-7.6.1

# if the directory exists
rm -r $SYMLINK_PATH

cp -sr $ACTUAL_PATH $SYMLINK_PATH
```

## Context

Why would I want to use a different directory for the XP distribution? In my case, it's because I'd like to package this for NixOS, which places it in the Nix store --- at `/nix/store/<hash>-enonic-xp-7.6.1` --- after patching it (which is required for the packaged Java executable to run) .

**Comment by pmi** [comment]
@thomasheartman Did you use snapcraft to install CLI ?

If yes, 
then we are not allowed to execute files outside of snap folder, so there is a [task](https://github.com/enonic/cli-enonic/issues/173) where I move entire `.enonic` folder inside the snap folder and leave a symlink to it at the usual `~/.enonic` to get rights to execute it. So custom location will not work.

If no,
then it looks like a bug to me too :)

**Comment by thomasheartman** [comment]
Ah, that's interesting. But no, I did not use Snap for this; I downloaded the binary from https://repo.enonic.com/public/com/enonic/cli/enonic/.
