### ISSUE TITLE
`enonic project deploy --dev` doesn't work if sandbox is already running

### ISSUE THREAD

**Issue by thomasheartman** [enonic/cli-enonic#272]
It seems that if you already have an instance of a sandbox running and you run `enonic project deploy --dev`, the `--dev` flag has no effect.

I couldn't find this mentioned in the docs anywhere, and the command's output doesn't mention it either.

I don't know what the best way to handle this is, but I think it would be good to at least document this. I think this should go in the regular documentation but also (and maybe especially) in the command's output. If there is an instance already running, I'd expect a note saying that the `--dev` flag has no effect.

I don't know how viable it is, but here's what I'd personally really like in terms of UX:

If it is possible to get the status of the running process and whether it's running in dev mode, the user could be warned about it not running in dev mode. They could then be prompted to kill the old process and start a new process instead. If it's not possible to get the dev mode status of the process, maybe the user should always be prompted to start a new process instead?

Any thoughts are appreciated. Cheers!

**Comment by sigdestad** [comment]
If sandbox is already running, I guess we could simply output a statement from CLI saying "because.. --dev flag ignored"?

**Comment by sigdestad** [comment]
We definetly don't want to restart the sandbox or anything like that.

**Comment by thomasheartman** [comment]
Yeah, I think just printing a little note about it if the user tries to use the `--dev` flag with a running sandbox would go a long way. It should also say in the docs somewhere.

What's the reason why we wouldn't want to offer the user the chance to restart the sandbox if it's already running? If the user tries to use the `--dev` flag with an existing sandbox running, isn't it likely that they'd want the sandbox to run in dev mode? Either that or they've misunderstood how it works, though some of that should be mitigated by putting a note about it in the command output.

Regarding wanting to restart the sandbox, that was the case for me, at least. It's doesn't take a lot of time, but you do have to quit/restart the sandbox manually. If the command offered to do it for me, that would have been nice. The CLI is really nice and easy to use in general, so I thought this could be a potential further improvement to it.

**Comment by sigdestad** [comment]
I guess it is hard to know if the SB is already running in dev mode, so we cannot really know if we should restart it or not. Lets keep it simple and output a mesage about igonoring flags. User can easily stop and start the sandbox if he wants to ctrl-c + run the command again

**Comment by alansemenov** [comment]
I made a [separate issue](https://github.com/enonic/cli-enonic/issues/274) for giving feedback to a user when sandbox is running. Also [added a note](https://developer.enonic.com/docs/enonic-cli/master/dev#deploy) about this to the description of the `project deploy` command
