### ISSUE TITLE
Give feedback when `project deploy` is executed with `dev` parameter 

### ISSUE THREAD

**Issue by alansemenov** [enonic/cli-enonic#274]
When "`project deploy`" is executed with "`--dev`" parameter, check if the sandbox is already running.
If it is, show the following text on a separate line under "_Deploying to sandbox..._". 

*`—dev` parameter is ignored. Check if the sandbox is running in dev mode.*

Use the same color as used in the message about last version check.

**Comment by sigdestad** [comment]
I suggest a slightly different feedback to avoid any confusion:

"Sandbox already running --dev parameter ignored"
