### ISSUE TITLE
Github bash cant select from lists

### ISSUE THREAD

**Issue by poi33** [enonic/cli-enonic#337]
Using git bash terminal i get a error: `Select failed: Incorrect function`
incorrect function 
![image](https://user-images.githubusercontent.com/3340349/135093189-8dfc30a9-f518-413a-a7f6-5aec3a1ca240.png)
or `Exiting: Incorrect function`
![image](https://user-images.githubusercontent.com/3340349/135095133-f47c1492-661a-4f7f-9f83-6dd98e59b0b9.png)

**Comment by alansemenov** [comment]
This one must be prioritised.

**Comment by pmi** [comment]
There is an open issue about that in https://github.com/go-survey/survey/issues/148
There is no mentioning that go-survey 2 will fix it either

**Comment by pmi** [comment]
Some of the possible alternatives are:
https://github.com/manifoldco/promptui
https://github.com/charmbracelet/bubbletea
https://github.com/erikgeiser/promptkit

**Comment by alansemenov** [comment]
[bubbletea](https://github.com/charmbracelet/bubbletea) looks like a good and well maintained alternative.
