### ISSUE TITLE
Build without sandbox

### ISSUE THREAD

**Issue by gbbirkisson** [enonic/cli-enonic#340]
Now the CLI refuses to build a project without a sandbox. This is fine on developer machines, but is very inconvenient in build pipelines where the JDK is provided for you. Downloading and installing a distro/sandbox every time the build runs is not ideal.

**Comment by pmi** [comment]
@gbbirkisson I suggest we allow building without sandbox with `--force` flag only when it runs in non-interactive mode which is perfect for pipelines.
In standard mode there are useful suggestions to user about missing sandbox or ability to create one.
@alansemenov ?

**Comment by alansemenov** [comment]
Yeah, I agree that building without a sandbox is a very specific requirement and might be confusing for a regular user.

**Comment by gbbirkisson** [comment]
Sounds good

**Comment by sigdestad** [comment]
How do we guarantee that such builds will be using the right version of Java SDK?

**Comment by pmi** [comment]
We can not guarantee that because system java will be used
But when no sandbox is set and `--force` flag is on, we only have 2 options:
- fail fast (what we do now)
- build using system java (useful for pipelines where projects are not created with cli)

**Comment by pmi** [comment]
One thing to note: **enonic project gradle** command passes all flags to gradle directly, so it doesn't know there's a `--force` flag and is not able to run non-interactively at all. Meaning it always suggests to choose a sandbox if missing.
