### ISSUE TITLE
Comparison of user input with a sandbox name should be case-insensitive

### ISSUE THREAD

**Issue by sgauruseu** [enonic/cli-enonic#404]
1.  type the command -  ```enonic sandbox create -v 7.12.2 test```
2.  Try to delete the just created sanbox , type the command  and the  name starts with uppercase```enonic sandbox delete -f Test```

![image](https://user-images.githubusercontent.com/3728712/231482855-ab5b08a5-0dbc-4d9a-8292-4c6a510825d5.png)

3. Try to create the sandbox with the name that starts with uppercase: 

![image](https://user-images.githubusercontent.com/3728712/231483944-6494327d-3380-4f03-a502-74f278a31f89.png)
 
Message ```Sandbox 'Test' created with distro 'enonic-xp-windows-sdk-7.12.2'.``` apears , but actually new sandbox was not created

![image](https://user-images.githubusercontent.com/3728712/231485955-913c9fb0-18a2-466e-95e0-103c72c99ba2.png)

**BUG** - Sanbox name should be case-sensetive

**Comment by jsi** [comment]
What happens if the version number is not the same?  -  I tried this on Mac.  There was a sandbox `testAAA` on version 7.9.2 with a number of content and apps installed.  Then I created `testaaa` with version 7.12.2 and got:
`Sandbox 'testaaa' created with distro 'enonic-xp-mac-sdk-7.12.2'.`
However, just like Siarheis test case above, there was no `testaaa` sandbox.  Instead, the `testAAA` sandbox had been upgraded to 7.12.2 with all the same contents and users as before.

**Comment by sgauruseu** [comment]
![image](https://user-images.githubusercontent.com/3728712/231496684-8f3ef0dc-1689-48bb-894e-5433ccda3b50.png)

The same issue is on Windows - sanbox with name ```Sandbox1``` upgrated to 7.12.2

**Comment by alansemenov** [comment]
The title of this issue is wrong. Sandbox names are already case-sensitive - they are created with correct case. It's the check for existing sandboxes that should be case-INsensitive.

**Comment by jsi** [comment]
@sgauruseu tested the previous case on Windows, and it behaved the same as Mac, so there does not seem to be a problem with different behaviour on different platforms, just strange behaviour / incorrect feedback when we use the same name with different case for sandbox names.

**Comment by jsi** [comment]
@alansemenov - Regarding your comment from yesterday:  Does this mean that we want case-sensitive names for sandboxes, but we will not allow any sandbox to have the same "case-INsensitive name"?

**Comment by pmi** [comment]
This is what happens on windows when you try creating folder **sandbox1** while **Sandbox1** is already present:

![Screenshot 2023-04-18 160520](https://user-images.githubusercontent.com/754221/232802628-784ebf66-f3ed-40fd-81e7-3178c129c7d7.png)

**Comment by pmi** [comment]
So I assume we will be safer cross platform when ignoring the case ourselves as well 😉

**Comment by alansemenov** [comment]
> @alansemenov - Regarding your comment from yesterday: Does this mean that we want case-sensitive names for sandboxes, but we will not allow any sandbox to have the same "case-INsensitive name"?

Yes - see Pavel's comment above. We want the same behaviour.
