### ISSUE TITLE
'Stopping sandbox' message  is repeating constantly even the sandbox is stopped 

### ISSUE THREAD

**Issue by sgauruseu** [enonic/cli-enonic#405]
1. Satrt asanbox `sand1`
2. Open a new terminal and try to start another sandbox `test`, the next message appears:
  `Sandbox 'sand1' is running, do you want to stop it? (Y/n)`  - click on 'Y'

BUG -  Sandbox `sand1` is stopped, but  the message  `Stopping sandbox 'sand1'...` is repeating constantly

![image](https://user-images.githubusercontent.com/3728712/231735974-b19076b4-5615-4bf9-9cbc-25b810ef213a.png)

**Comment by jsi** [comment]
Same bug on Mac: https://github.com/enonic/cli-enonic/issues/377

**Comment by sigdestad** [comment]
Yeah - this one is seriously annoying. Would be nice to get this fixed.
