### ISSUE TITLE
deploy project error on windows

### ISSUE THREAD

**Issue by mousavi007** [enonic/cli-enonic#408]
i create sample project with this command:
` enonic project create -r starter-myfirstwebapp`
when i go to project folder and deploy project with this command:
`enonic project deploy` 
get this error:
exec: "gradlew.bat": cannot run executable found relative to current directory
enonic xp version: 7.12.2
cli version: 2.4.0-RC4

**Comment by rymsha** [comment]
It is a problem with 2.4.0-RC4 - not an official release
version 2.3.3 does not have this problem.

**Comment by alansemenov** [comment]
@mousavi007 thank you for reporting this. the fix is now released in 2.4.0-RC5
