### ISSUE TITLE
Improve error message given when trying to create a snapshot with incorrect repository name

### ISSUE THREAD

**Issue by sgauruseu** [enonic/cli-enonic#410]
1.  Insert an incorrect name for  the name of the repository to snapshot: 
    `enonic snapshot create -a user1:password123 -r com.test`

BUG  -  500 error appears:

![image](https://user-images.githubusercontent.com/3728712/232493233-7181b383-c412-42dd-8a28-a2995db561d1.png)

**Comment by pmi** [comment]
This is what happens when user and password **are valid**, but the repository **is not**

And this what happens when the user/pass is invalid:
```
.\enonic.exe snapshot create -a test:com -r test.com
Creating snapshot...User and password are not valid.
? Authentication token (<user>:<password>):
```

**Comment by pmi** [comment]
Fixed the error format to be more human friendly
```
enonic.exe snapshot create -a pmi:pmi1234567 -r com.enonic.cmso
Creating snapshot...Failure: no such index
```
