### ISSUE TITLE
sandbox create -v doesn't accept full distro name

### ISSUE THREAD

**Issue by ComLock** [enonic/cli-enonic#420]
`enonic sandbox create --version mac-arm64-sdk-7.12.1 MySandbox`

Doesn't work, and simply enters interactive mode.

**Comment by alansemenov** [comment]
@ComLock why do you need full distro name? the idea was to make it simple, so that you do `enonic sandbox create --version 7.12.1 MySandbox` and CLI automatically finds a distro of specified version for your platform. no one knows/will use full distro name.

**Comment by ComLock** [comment]
Because that is the name that is in the list...
