### ISSUE TITLE
Done message appears after starting a non-existing application

### ISSUE THREAD

**Issue by sgauruseu** [enonic/cli-enonic#444]
1. Create then start a sandbox, create an user(admin)
2. Install Superhero app
3. Stop Superhero app
4.  run the command: `enonic app start com.enonic.app.superhero -a user1:password123`
5. run the same command with non-existent app name

**BUG** - `Done` is shown after starting  a non-existent application

![image](https://github.com/enonic/cli-enonic/assets/3728712/cc381b62-51c0-4a8b-9f11-c83792ce7f8d)

**Comment by pmi** [comment]
XP always returns 204 (No Content) status to `app/start` and `app/stop` requests so there is no way to tell if the app exists/was started.

Therefore message says: 

**Requesting** start "app key"...**Done**.

Where done means that request has finished.
