### ISSUE TITLE
Use Solution Templates when creating a new sandbox

### ISSUE THREAD

**Issue by alansemenov** [enonic/cli-enonic#459]
* Selection of a solution template should be the first step of sandbox creation (before providing a sandbox name)
* Default behaviour is that user always have to select a template:
```
Select a template for the new sandbox:
* Headless 
* CMS
* ...
* Clean/empty
```
* Support an argument to skip selection of a template: `--skip-template`
* Support a parameter (`-t` or `--template`) to specify a template: `-t headless` or `--template nextjs`. Template name should match value of the `_name` field in the Guillotine response. If no match found, show the full list of templates to choose from.

**Comment by pmi** [comment]
Decided to save the selected template in a JSON format as an app id and config.
