### ISSUE TITLE
Potential bug with running `upgrade` command with Windows/Scoop

### ISSUE THREAD

**Issue by alansemenov** [enonic/cli-enonic#478]
https://discuss.enonic.com/t/enonic-cli-2-7-0-has-been-released/3098/4

Seems like CLI doesn't execute correct command for upgrading CLI via scoop?

**Comment by pmi** [comment]
It required a hack to downgrade version in scoop because it can not do it natively, but the `enonic upgrade` did invoke `scoop update enonic` which eventually failed because of the hack.

But that still proves the fact that `enonic upgrade` works as expected, at least in version `2.6.1`.
