### ISSUE TITLE
`project create` command should not start linked sandbox

### ISSUE THREAD

**Issue by sigdestad** [enonic/cli-enonic#536]
Running the following command: `enonic create my.first.r4xp -r starter-react4xp -s r4xptutorial -f` will automatically start the linked sandbox, but it should not.

FYI:
Commands like `enonic (project) create -r starter-react4xp -f` works fine, as these say you have to specify sandbox
Running `enonic (project) create` also works fine, as it will ask for every step (including creating and starting sandbox)

**Comment by pmi** [comment]
@sigdestad Why not ? There is a reason it behaves this way:

Flag `-f` means default answer to all questions. 
And there is a question at the end of creation of a project whether you want to run it with the default answer Y.
So it will break these rules if we make it behave differently here.

It tries to start it without the sandbox provided as well, but complains about it missing in the last line:
```
enonic create my.first.r4xp -r starter-react4xp -f
...
Sandbox distro and name must be set!
```

**Comment by alansemenov** [comment]
The question is not in how "-f" flag works. It's about that CLI should suggest to start a sandbox only if sandbox was created as a part of the command execution. If a project is linked to an existing sandbox (as with `-s r4xptutorial` from the example above), it should not suggest to start it because no sandbox was created.

**Comment by pmi** [comment]
Hmm, I thought the reason it asked was you just created a project and wanted to deploy it ? 
Not because you had to create a sandbox on the way 😕

**Comment by pmi** [comment]
Ok, I thing I got it -- we only want to ask about starting sandbox after creating sandbox ?

**Comment by alansemenov** [comment]
> Ok, I think I got it -- we only want to ask about starting sandbox after creating sandbox and nothing else ?

Correct
