### ISSUE TITLE
Check sandbox name before suggesting to stop it

### ISSUE THREAD

**Issue by alansemenov** [enonic/cli-enonic#542]
If the sandbox that is currently running is the same as the one CLI is trying to start don't suggest stopping the running one.

**Comment by pmi** [comment]
This issue is most likely related to #535 and should be fixed along with it.

Because CLI verifies sandbox name, PID and process name and asks to stop it only if any of them has changed.

**Comment by alansemenov** [comment]
Will be fixed in https://github.com/enonic/cli-enonic/issues/535
