### ISSUE TITLE
Add `SnapshotsVacuumTask` task for `vacuum` command

### ISSUE THREAD

**Issue by anatol-sialitski** [enonic/cli-enonic#577]
Add the `SnapshotsVacuumTask` to the `vacuum` command. This task should be included in the list of default tasks.

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Added the SnapshotsVacuumTask to the list of default tasks in the vacuum command. This task will now be included when running the vacuum command with the --blob flag.

You can review changes in this commit: https://github.com/mnmnk43434/enonic-cli-enonic-577/commit/26710130f6464cc08fb7fba2f47b4deecfd5727e.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
