### ISSUE TITLE
Enonic CLI - Session

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/cli-enonic#62]
We should not pass the credentials everytime but store and transfer the session ID instead

Reasons:
* It creates a session everytime
* We need to specify the credentials for each method
* Obvious problem is the way the load works

Proposition:
* We store sessionID per remote
* Make the ``-a``option optional for management commands
* On a management command
  * Check if there is a sessionID stored for this remote.
  * If there is none and no credential was passed -> Ask for the credentials. 
  * We send the request
  * If we get a 401 status and there was no credentials passed -> Display that the user needs to put the credentials and resend the request
  * If we get a 200 and there were credentials passed -> Store the sessionID
* For progress update, Pass the sessionID
* Remove the second credentials for load

**Comment by sigdestad** [comment]
We have now created use of system variables, so the session concept should not be needed as things are now. Closing this task
